CREATE TABLE [dbo].[Location]
(
	[Id] UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	[Latitude] DECIMAL(18, 10) NOT NULL,
	[Longitude] DECIMAL(18, 10) NOT NULL,
	[AddedAt] DATETIME NOT NULL,
	[AddedBy] INT FOREIGN KEY REFERENCES [User](Id) NOT NULL,
)
