CREATE TABLE [dbo].[User]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	[Username] VARCHAR(50) NOT NULL UNIQUE,
	[Email] VARCHAR(100) NOT NULL UNIQUE,
	[Password] VARCHAR(100) NOT NULL,
	[IsAdmin] BIT NOT NULL,
	[RegisteredAt] DATETIME NOT NULL,
)
