CREATE TABLE [dbo].[Vote]
(
	[Id] UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	[UserId] INT FOREIGN KEY REFERENCES [User](Id),
	[Type] INT FOREIGN KEY REFERENCES [VoteType](Id),
	[AddedAt] DATETIME NOT NULL,
)
