CREATE TABLE [dbo].[Vote]
(
	[Id] UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	[UserId] INT FOREIGN KEY REFERENCES [User](Id) NOT NULL,
	[Type] INT FOREIGN KEY REFERENCES [VoteType](Id) NOT NULL,
	[LocationId] UNIQUEIDENTIFIER FOREIGN KEY REFERENCES [Location](Id) NOT NULL,
	[AddedAt] DATETIME NOT NULL,
)
