@startuml C4_Elements
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
!include DEVICONS/msql_server.puml
!include DEVICONS/dotnet.puml
!include DEVICONS/html5.puml
!include FONTAWESOME/mobile.puml

SHOW_PERSON_OUTLINE()
HIDE_STEREOTYPE()
LAYOUT_TOP_DOWN()

AddContainerTag(api_tag, $shape=EightSidedShape())

Person(user, "User", "Probably person alergic to ambrosia")
Person(admin, "Administrator", "Sees everything, knows everything")
System_Boundary(system, "Ambrosia Alert"){
    Container(api, "Web API", "ASP.NET", "Where magic happens", $sprite=dotnet, $tags="api_tag")
    Container(app, "Progressive Web App", "Blazor Web Assembly", "Your own ambrosia alert in your phone", $sprite=mobile)
    Container(dashboard, "Admin Dashboard", "ASP.NET MVC", "Where they see everything", $sprite=html5)
    ContainerDb(db, "Database", "Microsoft SQL Server", "All your data stored SECURELY", $sprite=msql_server)
}

Rel(user, app, "Request", "HTTP")
Rel(app, user, "Notification", "SignalR")
Rel(admin, dashboard, "Request", "HTTP")
Rel(app, api, "Request", "HTTP")
Rel(dashboard, api, "Request", "HTTP")
Rel_R(api, db, "Query", "SQL")

@enduml